#!/usr/bin/env bash

pkill eww
pkill myshell
eww daemon


# Start Eww
# open on primary monitor
eww open bar
eww open desktop
eww open notifications_popup
hyprctl setcursor 'Bibata-Modern-Ice' 24

$HOME/.config/eww/scripts/myshell/myshell --eww --file
